import Link from 'next/link'
import './globals.css'
import styles from './layout.module.css'
import { Be_Vietnam_Pro } from 'next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const vietnamPro = Be_Vietnam_Pro({
  weight: ['400', '500', '700'],
  style: 'normal',
  subsets: ['latin']
})

export default function RootLayout({ children }) {
  return (
    <html lang='es' className={vietnamPro.className}>
      <body>
        <header className={styles.header}>
          <div className={`container ${styles.container}`}>
            <div>
              <Link href='/' className={styles.logoLink}>
                <img src='/icon.png' alt='Logo of Hirenix' />
                <h2>Hirenix</h2>
              </Link>
            </div>
            <nav className={styles.navigation}>
              <Link href='/'>Inicio</Link>
              <Link href='/explorar'>Explorar</Link>
              <Link href='/lab'>Laboratorio</Link>
              <Link href='/explorar'>Reclutar</Link>
            </nav>
            <div className={styles.loginContainer}>
              <button className={styles.login}>Ingresar</button>
              <button className={styles.register}>Registrarse</button>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
